name: publish to vs marketplace
on:
  release:
    types: [published]

jobs:
  release:
    runs-on: ubuntu-latest
    environment:
        name: vsce
        url: https://marketplace.visualstudio.com/items?itemName=luraph.luraph-vscode
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Setup node.js
        uses: actions/setup-node@v4
        with:
          node-version: ">=18"
          cache: "yarn"

      - name: Install dependencies
        run: yarn install --immutable --immutable-cache --check-cache

      - name: Package VSIX
        run: yarn run package

      - name: Upload VSIX to GitHub Release
        uses: softprops/action-gh-release@v2
        with:
            fail_on_unmatched_files: true
            files: |
              *.vsix

      - name: Publish to VS marketplace
        run: yarn run deploy
        env:
            VSCE_PAT: ${{ secrets.VSCE_PAT }}